INSERT INTO ACTIVO (ID, NOMBRE, TAMANO, TIPO, URL, CUENTAID) VALUES (501, 'Manual PDF', 1, 'Documento', 'https://plytix.com/manual501.pdf', 1);
INSERT INTO ACTIVO (ID, NOMBRE, TAMANO, TIPO, URL, CUENTAID) VALUES (502, 'Imagen Producto', 2, 'Imagen', 'https://plytix.com/imagen502.png', 1);
INSERT INTO ACTIVO (ID, NOMBRE, TAMANO, TIPO, URL, CUENTAID) VALUES (503, 'Garantía', 1, 'Documento', 'https://plytix.com/garantia503.pdf', 2);
INSERT INTO ATRIBUTO (ID, NOMBRE, TIPO, CREADO, CUENTAID) VALUES (101, 'Color', 'Texto', TO_DATE('2023-03-01', 'YYYY-MM-DD'), 1);
INSERT INTO ATRIBUTO (ID, NOMBRE, TIPO, CREADO, CUENTAID) VALUES (102, 'Peso', 'Número', TO_DATE('2023-05-15', 'YYYY-MM-DD'), 1);
INSERT INTO ATRIBUTO (ID, NOMBRE, TIPO, CREADO, CUENTAID) VALUES (103, 'Material', 'Texto', TO_DATE('2024-01-10', 'YYYY-MM-DD'), 2);